// Code generated by command: go run search.go. DO NOT EDIT.

#include "textflag.h"

// func searchAVX2(blocks []byte, key uint32, numBlocks int) int
// Requires: AVX, AVX2
TEXT ·searchAVX2(SB), NOSPLIT, $0-48
	MOVQ         blocks_base+0(FP), AX
	MOVL         key+24(FP), CX
	MOVQ         numBlocks+32(FP), DX
	TESTQ        DX, DX
	JZ           notFound
	VMOVD        CX, X0
	VPBROADCASTD X0, Y0
	MOVQ         $0x00000000ffffffff, CX
	VMOVD        CX, X1
	VPBROADCASTD X1, Y1
	XORQ         CX, CX

traversalLoop:
	CMPQ      CX, DX
	JAE       notFound
	MOVQ      CX, SI
	SHLQ      $0x06, SI
	ADDQ      AX, SI
	VMOVDQU   (SI), Y2
	VPCMPEQD  Y0, Y2, Y3
	VMOVMSKPS Y3, DI
	TESTL     DI, DI
	JNZ       foundInFirstHalf
	VMOVDQU   32(SI), Y4
	VPCMPEQD  Y0, Y4, Y3
	VMOVMSKPS Y3, DI
	TESTL     DI, DI
	JNZ       foundInSecondHalf
	MOVQ      $0x0000000000000010, SI
	VPCMPGTD  Y0, Y2, Y3
	VMOVMSKPS Y3, DI
	TESTL     DI, DI
	JNZ       greaterInFirstHalf
	VPCMPEQD  Y1, Y2, Y2
	VMOVMSKPS Y2, DI
	TESTL     DI, DI
	JNZ       sentinelInFirstHalf
	VPCMPGTD  Y0, Y4, Y3
	VMOVMSKPS Y3, DI
	TESTL     DI, DI
	JNZ       greaterInSecondHalf
	VPCMPEQD  Y1, Y4, Y2
	VMOVMSKPS Y2, DI
	TESTL     DI, DI
	JNZ       sentinelInSecondHalf
	JMP       calculateNext

greaterInFirstHalf:
	BSFL DI, SI
	JMP  calculateNext

greaterInSecondHalf:
	BSFL DI, SI
	ADDQ $0x08, SI
	JMP  calculateNext

sentinelInFirstHalf:
	BSFL DI, SI
	JMP  calculateNext

sentinelInSecondHalf:
	BSFL DI, SI
	ADDQ $0x08, SI

calculateNext:
	IMUL3Q $0x11, CX, CX
	ADDQ   SI, CX
	INCQ   CX
	JMP    traversalLoop

foundInFirstHalf:
	BSFL DI, BX
	MOVQ CX, AX
	SHLQ $0x04, AX
	MOVL BX, CX
	ADDQ CX, AX
	VZEROUPPER
	MOVQ AX, ret+40(FP)
	RET

foundInSecondHalf:
	BSFL DI, BX
	MOVQ CX, AX
	SHLQ $0x04, AX
	MOVL BX, CX
	ADDQ CX, AX
	ADDQ $0x08, AX
	VZEROUPPER
	MOVQ AX, ret+40(FP)
	RET

notFound:
	VZEROUPPER
	MOVQ $-1, AX
	MOVQ AX, ret+40(FP)
	RET

// func searchSSE(blocks []byte, key uint32, numBlocks int) int
// Requires: SSE2
TEXT ·searchSSE(SB), NOSPLIT, $0-48
	MOVQ   blocks_base+0(FP), AX
	MOVL   key+24(FP), CX
	MOVQ   numBlocks+32(FP), DX
	TESTQ  DX, DX
	JZ     sseNotFound
	MOVD   CX, X0
	PSHUFD $0x00, X0, X0
	MOVQ   $0x00000000ffffffff, CX
	MOVD   CX, X1
	PSHUFD $0x00, X1, X1
	XORQ   CX, CX

sseTraversalLoop:
	CMPQ     CX, DX
	JAE      sseNotFound
	MOVQ     CX, SI
	SHLQ     $0x06, SI
	ADDQ     AX, SI
	MOVOU    (SI), X3
	MOVO     X0, X2
	PCMPEQL  X3, X2
	PMOVMSKB X2, DI
	TESTL    DI, DI
	JNZ      sseFoundInChunk0
	MOVOU    16(SI), X4
	MOVO     X0, X2
	PCMPEQL  X4, X2
	PMOVMSKB X2, DI
	TESTL    DI, DI
	JNZ      sseFoundInChunk1
	MOVOU    32(SI), X5
	MOVO     X0, X2
	PCMPEQL  X5, X2
	PMOVMSKB X2, DI
	TESTL    DI, DI
	JNZ      sseFoundInChunk2
	MOVOU    48(SI), X6
	MOVO     X0, X2
	PCMPEQL  X6, X2
	PMOVMSKB X2, DI
	TESTL    DI, DI
	JNZ      sseFoundInChunk3
	MOVQ     $0x0000000000000010, SI
	MOVO     X3, X2
	PCMPGTL  X0, X2
	PMOVMSKB X2, DI
	TESTL    DI, DI
	JNZ      sseGtChunk0
	MOVO     X1, X2
	PCMPEQL  X3, X2
	PMOVMSKB X2, DI
	TESTL    DI, DI
	JNZ      sseSentChunk0
	MOVO     X4, X2
	PCMPGTL  X0, X2
	PMOVMSKB X2, DI
	TESTL    DI, DI
	JNZ      sseGtChunk1
	MOVO     X1, X2
	PCMPEQL  X4, X2
	PMOVMSKB X2, DI
	TESTL    DI, DI
	JNZ      sseSentChunk1
	MOVO     X5, X2
	PCMPGTL  X0, X2
	PMOVMSKB X2, DI
	TESTL    DI, DI
	JNZ      sseGtChunk2
	MOVO     X1, X2
	PCMPEQL  X5, X2
	PMOVMSKB X2, DI
	TESTL    DI, DI
	JNZ      sseSentChunk2
	MOVO     X6, X2
	PCMPGTL  X0, X2
	PMOVMSKB X2, DI
	TESTL    DI, DI
	JNZ      sseGtChunk3
	MOVO     X1, X2
	PCMPEQL  X6, X2
	PMOVMSKB X2, DI
	TESTL    DI, DI
	JNZ      sseSentChunk3
	JMP      sseCalculateNext

sseGtChunk0:
	BSFL DI, SI
	SHRQ $0x02, SI
	JMP  sseCalculateNext

sseSentChunk0:
	BSFL DI, SI
	SHRQ $0x02, SI
	JMP  sseCalculateNext

sseGtChunk1:
	BSFL DI, SI
	SHRQ $0x02, SI
	ADDQ $0x04, SI
	JMP  sseCalculateNext

sseSentChunk1:
	BSFL DI, SI
	SHRQ $0x02, SI
	ADDQ $0x04, SI
	JMP  sseCalculateNext

sseGtChunk2:
	BSFL DI, SI
	SHRQ $0x02, SI
	ADDQ $0x08, SI
	JMP  sseCalculateNext

sseSentChunk2:
	BSFL DI, SI
	SHRQ $0x02, SI
	ADDQ $0x08, SI
	JMP  sseCalculateNext

sseGtChunk3:
	BSFL DI, SI
	SHRQ $0x02, SI
	ADDQ $0x0c, SI
	JMP  sseCalculateNext

sseSentChunk3:
	BSFL DI, SI
	SHRQ $0x02, SI
	ADDQ $0x0c, SI

sseCalculateNext:
	IMUL3Q $0x11, CX, CX
	ADDQ   SI, CX
	INCQ   CX
	JMP    sseTraversalLoop

sseFoundInChunk0:
	BSFL DI, BX
	SHRQ $0x02, BX
	MOVQ CX, AX
	SHLQ $0x04, AX
	MOVL BX, CX
	ADDQ CX, AX
	MOVQ AX, ret+40(FP)
	RET

sseFoundInChunk1:
	BSFL DI, BX
	SHRQ $0x02, BX
	MOVQ CX, AX
	SHLQ $0x04, AX
	MOVL BX, CX
	ADDQ CX, AX
	ADDQ $0x04, AX
	MOVQ AX, ret+40(FP)
	RET

sseFoundInChunk2:
	BSFL DI, BX
	SHRQ $0x02, BX
	MOVQ CX, AX
	SHLQ $0x04, AX
	MOVL BX, CX
	ADDQ CX, AX
	ADDQ $0x08, AX
	MOVQ AX, ret+40(FP)
	RET

sseFoundInChunk3:
	BSFL DI, BX
	SHRQ $0x02, BX
	MOVQ CX, AX
	SHLQ $0x04, AX
	MOVL BX, CX
	ADDQ CX, AX
	ADDQ $0x0c, AX
	MOVQ AX, ret+40(FP)
	RET

sseNotFound:
	MOVQ $-1, AX
	MOVQ AX, ret+40(FP)
	RET
